### ISSUE TITLE
TypeError: list is not a dataclass and cannot be turned into one.

### ISSUE THREAD

**Issue by FranzForstmayr** [lovasoa/marshmallow_dataclass#140] opened 2021-05-07 07:41 UTC
Starting with Release of Python3.9 `list` is a generic alias type and `typing.List` becomes deprectated.

However, marshmallow_dataclass is unable to work with the construct `list[SomeOtherDataclass]`, whereas `List[SomeOtherDataclass]` works.

**Comment by lovasoa** [comment] 2021-05-07 07:53
Duplicate of https://github.com/lovasoa/marshmallow_dataclass/issues/136

**Closed by lovasoa** 2021-05-07 07:53 UTC
