### ISSUE TITLE
@dataclass monkeypatches other code

### ISSUE THREAD

**Issue by jonashaag** [lovasoa/marshmallow_dataclass#95] opened 2020-08-11 15:11 UTC
I think this is identical to #51:

```pycon
>>> from pathlib import Path
>>> Path("/tmp")
PosixPath('/tmp')
>>> from marshmallow_dataclass import dataclass
>>> @dataclass
... class X:
...  x: Path
...
>>> Path("/tmp")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes 1 positional argument but 2 were given
```

It changes `pathlib.Path.__init__` 😱

**Comment by lovasoa** [comment] 2020-08-11 15:52
This is indeed the same bug as #51. 
It is problematic, but I'd like a fix that is as backward-compatible as possible.
@jonashaag, if you want to submit a PR to fix this, I suggest you add a way to keep track of the class on which `class_schema` was initially called, and then for all subsequent (nested) calls, check that the `.__module__` of the class is the same as the one of the initial class before calling `dataclasses.dataclass` on it.

Closing as a duplicate of #51, but feel free to still comment below.

**Closed by lovasoa** 2020-08-11 15:52 UTC
