### ISSUE TITLE
Issue when using dataclass with InitVar fields

### ISSUE THREAD

**Issue by scoulomb** [lovasoa/marshmallow_dataclass#89] opened 2020-06-05 15:51 UTC
**Description**

If we have a dataclass with init var field
`model_schema().load()` is not working properly

**Steps to reproduce**

``````python

import json
import unittest
from dataclasses import dataclass, field, InitVar
from typing import Any, Dict

import marshmallow_dataclass


@dataclass
class Sample:
    welcome_message: str = field(init=False)
    name: InitVar[str]

    def __post_init__(self,
                      name: str
                      ) -> None:
        self.welcome_message = f"Welcome {name}"

    def as_json_string(self):
        return json.dumps(self, default=lambda o: o.__dict__)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Sample':
        model_schema = marshmallow_dataclass.class_schema(cls)
        return model_schema().load(data)


class TestModel(unittest.TestCase):

    def test_json_to_object_to_json(self):
        test = Sample("John")
        test_to_json = json.loads(test.as_json_string())
        print(test_to_json)
        print(test)
        self.assertEqual(test, Sample.from_dict(test_to_json))


if __name__ == '__main__':
    unittest.main()

``````

Error is 

````
marshmallow.exceptions.ValidationError: {'welcome_message': ['Unknown field.']}
````

**Comment by lovasoa** [comment] 2020-06-05 20:24
@scoulomb : isn't this a duplicate of #83 ?

**Comment by scoulomb** [comment] 2020-06-05 22:42
> @scoulomb : isn't this a duplicate of #83 ?

@lovasoa Thanks a lot for having a look

Indeed, if we add  `class Meta` as in the  issue: https://github.com/lovasoa/marshmallow_dataclass/issues/83
prevents to have the error: `marshmallow.exceptions.ValidationError: {'name': ['Unknown field.']}`
Thanks so much for the Tip :) !

Actually, I realized the issue here is more complex.
It is due to fact, we do the combination of field(init=false) AND InitVar.

Because I guess we use JSON key and object field name to rebuild the object

Indeed in this case

-  Generated constructor has name parameter, but not welcome message parameter (because of field(init = false...)

- Serialized JSON has welcome_message key but not name key (because of init var)
This is on purpose. It enables to compute an object attribute based on an input parameter of the constructor.
We we do not want to have this input parameter as class attribute. 

But issue is that breaks deserialization because when rebuilding the object
- serialized JSONcontains welcome message key which is not in the object constructor
- Constructor has name field, which is not in the serialized JSON, thus the issue

Even if it was it would have to know the initial logic
Consequently, workaround for the issue is to:
- use class meta
- Arrange the JSON with computed field before calling from dict

**Comment by scoulomb** [comment] 2020-06-05 22:45
Here is the previous reproduction with the workaround: 

```python
import json
import unittest
from dataclasses import dataclass, field, InitVar
from typing import Any, Dict

import marshmallow_dataclass


@dataclass
class Sample:
    welcome_message: str = field(init=False, default="ggg")
    name: InitVar[str]

    def __post_init__(self,
                      name: str
                      ) -> None:
        # print(name)
        self.welcome_message = f"Welcome {name}"

    def as_json_string(self):
        return json.dumps(self, default=lambda o: o.__dict__)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Sample':
        model_schema = marshmallow_dataclass.class_schema(cls)
        return model_schema().load(data)

    class Meta:
        load_only = additional = ('name',)

    @classmethod
    def prepare_serialization(cls, serialized_dict: Dict[str, Any]):
        serialized_dict["name"] = serialized_dict["welcome_message"].partition(" ")[2]
        del serialized_dict["welcome_message"]
        return serialized_dict


class TestModel(unittest.TestCase):

    def test_json_to_object_to_json(self):
        test = Sample("John")
        test_to_json = json.loads(test.as_json_string())
        print(f"object  {test}")
        print(f"serialized  {test_to_json}")
        # deserialized_object = Sample.from_dict(test_to_json) # => this will lead to marshmallow.exceptions.ValidationError: {'welcome_message': ['Unknown field.']}
        deserialized_object = Sample.from_dict(Sample.prepare_serialization((test_to_json)))
        print(f"deserialized_object  {deserialized_object}")
        self.assertEqual(test, deserialized_object)


if __name__ == '__main__':
    unittest.main()

```

Where output is


Output is
```shell

Ran 1 test in 0.002s

OK
object  Sample(welcome_message='Welcome John')
serialized  {'welcome_message': 'Welcome John'}
deserialized_object  Sample(welcome_message='Welcome John')
```

**Comment by scoulomb** [comment] 2020-06-05 22:45
Can we be more elegant?

**Comment by lovasoa** [comment] 2020-06-05 22:50
OK, closing as a duplicate of #83

We can continue the discussion  there

**Closed by lovasoa** 2020-06-05 22:50 UTC
