### ISSUE TITLE
Odd Behavior with pathlib.Path

### ISSUE THREAD

**Issue by anordin95** [lovasoa/marshmallow_dataclass#105] opened 2020-09-24 18:08 UTC
```
from pathlib import Path
import marshmallow_dataclass

test = Path('hi')

@marshmallow_dataclass.dataclass
class Link:
	p: Path

test = Path('hi')

```

**Traceback**
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    test = Path('hi')
TypeError: __init__() takes 1 positional argument but 2 were given
```

The second attempt to instantiate a Path object fails. I suspect the call to `@marshmallow_dataclass.dataclass` is somehow modifying `Path`. 

I tried to `pdb` the execution and step through to understand how this could be happening, but I didn't find any valuable leads.

**Comment by lovasoa** [comment] 2020-09-24 18:25
Duplicate of https://github.com/lovasoa/marshmallow_dataclass/issues/51

**Closed** 2020-09-24 18:25 UTC

**Comment by anordin95** [comment] 2020-09-24 19:30
Thanks!
